using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.Json;
using OneOS.Runtime.Language;
using OneOS.Runtime.Language.Ast;
using OneOS.Runtime.Language.Models;

namespace OneOS.Runtime.Driver
{
    // The DIFT policy an IDM-enabled JavaScript agent bootstraps with, as a CommonJS module that instrument.js
    // requires:
    //
    //   module.exports = { labellers: { <name>: (<params>) => <label>, ... }, rules: ['a -> b', ...] };
    //
    // Both come from the graph's DSL. `labellers` has every named labeller the program declares, translated
    // to JavaScript and keyed by its name (the program's injection points name them); a labeller returns its
    // label's name as a string. `rules` is the declared label order (LabelLattice.FlowRules).
    // Each labeller is self-contained: the instrumenter copies it into the program by its source text
    // (Turnstile.stringify), so it can't refer to anything else in this module. One that uses join, meet or leq
    // carries the lattice tables in its own body.
    public static class DiftPolicyModule
    {
        public static string Generate(CompiledGraph graph, string agentUri)
        {
            var L = graph.Lattice;
            var js = new StringBuilder();
            js.AppendLine($"// DIFT policy of {agentUri}, generated by OneOS from graph {graph.Name}.");
            js.AppendLine("'use strict';");
            js.AppendLine("module.exports = {");
            js.AppendLine("  labellers: {");
            foreach (var (name, spec) in graph.Labellers.OrderBy(kv => kv.Key, StringComparer.Ordinal))
            {
                if (spec.SourceText != null) js.AppendLine($"    // {spec.SourceText.ReplaceLineEndings(" ")}");
                js.AppendLine($"    {Json(name)}: {Labeller(spec, L)},");
            }
            js.AppendLine("  },");
            js.AppendLine($"  rules: {Json(L.FlowRules())},");
            js.AppendLine("};");
            return js.ToString();
        }

        // One labeller as a JavaScript arrow function.
        public static string Labeller(LabelSpec spec, LabelLattice lattice)
        {
            var parameters = (spec.Parameters ?? Array.Empty<LabellerParamInfo>()).ToDictionary(p => p.Name, p => Identifier(p.Name));
            var head = $"({string.Join(", ", parameters.Values)}) =>";
            var body = Expr(spec.Body!, parameters, lattice);
            return UsesLatticeBuiltins(spec.Body!, parameters) ? $"{head} {{ {LatticeHelpers(lattice)} return {body}; }}" : $"{head} {body}";
        }

        // The lattice and join, meet and leq over label names, as statements.
        private static string LatticeHelpers(LabelLattice L) =>
            $"const $labels = {Json(L.Labels)}; " +
            $"const $leqTable = {Json(L.LeqTable)}; " +
            $"const $joinTable = {Json(L.JoinTable.Select(row => row.Select(j => j >= 0 ? j : L.TopIndex)))}; " +
            $"const $meetTable = {Json(L.MeetTable)}; " +
            "const $index = (l) => { const i = $labels.indexOf(l); if (i < 0) throw new Error(`unknown label '${l}'`); return i; }; " +
            "const $leq = (a, b) => $leqTable[$index(a)][$index(b)]; " +
            "const $join = (a, b) => $labels[$joinTable[$index(a)][$index(b)]]; " +
            "const $meet = (a, b) => $labels[$meetTable[$index(a)][$index(b)]];";

        private static bool UsesLatticeBuiltins(Expression e, IReadOnlyDictionary<string, string> parameters) => e switch
        {
            CallExpr { Callee: IdentExpr { Name: "join" or "meet" or "leq" } fn } when !parameters.ContainsKey(fn.Name) => true,
            CallExpr c => (c.Callee is MemberExpr m && UsesLatticeBuiltins(m.Target, parameters)) || c.Args.Any(a => UsesLatticeBuiltins(a, parameters)),
            MemberExpr m => UsesLatticeBuiltins(m.Target, parameters),
            UnaryExpr u => UsesLatticeBuiltins(u.Operand, parameters),
            BinaryExpr b => UsesLatticeBuiltins(b.Left, parameters) || UsesLatticeBuiltins(b.Right, parameters),
            TernaryExpr t => UsesLatticeBuiltins(t.Condition, parameters) || UsesLatticeBuiltins(t.Then, parameters) || UsesLatticeBuiltins(t.Else, parameters),
            _ => false,
        };

        // DSL expression → JavaScript expression, with the semantics of ConcreteEval: labels are their names
        // (strings), `==` is strict equality, `contains` is `includes` (on strings and lists), and join, meet and
        // leq use the lattice tables of LatticeHelpers. Every compound expression is parenthesized.
        private static string Expr(Expression e, IReadOnlyDictionary<string, string> parameters, LabelLattice L)
        {
            string E(Expression x) => Expr(x, parameters, L);
            switch (e)
            {
                case StringLiteral s: return Json(s.Value);
                case IntLiteral i: return i.Value.ToString(CultureInfo.InvariantCulture);
                case FloatLiteral f: return f.Value.ToString("R", CultureInfo.InvariantCulture);
                case BoolLiteral b: return b.Value ? "true" : "false";
                case DurationLiteral d: return d.Nanoseconds.ToString(CultureInfo.InvariantCulture);
                case SizeLiteral z: return z.Bytes.ToString(CultureInfo.InvariantCulture);
                case IdentExpr id when parameters.TryGetValue(id.Name, out var p): return p;
                case IdentExpr id when L.Contains(id.Name): return Json(id.Name);
                case MemberExpr m: return $"{E(m.Target)}.{m.Name}";
                case CallExpr { Callee: IdentExpr { Name: "join" or "meet" or "leq" } fn } c when c.Args.Count == 2 && !parameters.ContainsKey(fn.Name):
                    return $"${fn.Name}({E(c.Args[0])}, {E(c.Args[1])})";
                case CallExpr { Callee: MemberExpr { Name: "startsWith" or "endsWith" or "contains" } m } c when c.Args.Count == 1:
                    return $"{E(m.Target)}.{(m.Name == "contains" ? "includes" : m.Name)}({E(c.Args[0])})";
                case UnaryExpr u: return $"({u.Op}{E(u.Operand)})";
                case BinaryExpr b:
                    var op = b.Op switch { "==" => "===", "!=" => "!==", _ => b.Op };
                    return $"({E(b.Left)} {op} {E(b.Right)})";
                case TernaryExpr t: return $"({E(t.Condition)} ? {E(t.Then)} : {E(t.Else)})";
            }
            // The compiler rejects anything else; fail at the call rather than while loading the module.
            return $"(() => {{ throw new Error({Json($"unsupported labeller expression: {e.GetType().Name}")}); }})()";
        }

        // DSL identifiers are valid JavaScript identifiers, except for JavaScript's reserved words and the
        // helpers' `$` names.
        private static string Identifier(string name) => Reserved.Contains(name) ? name + "_" : name;

        private static readonly HashSet<string> Reserved = new(StringComparer.Ordinal)
        {
            "arguments", "await", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete",
            "do", "else", "enum", "eval", "export", "extends", "false", "finally", "for", "function", "if", "implements",
            "import", "in", "instanceof", "interface", "let", "new", "null", "package", "private", "protected", "public",
            "return", "static", "super", "switch", "this", "throw", "true", "try", "typeof", "undefined", "var", "void",
            "while", "with", "yield",
        };

        private static string Json<T>(T value) => JsonSerializer.Serialize(value);
    }
}
